### ISSUE TITLE
Get frontend started

### ISSUE THREAD

**Issue by ben594** [ben594/CS316-open#2]
- Currently the frontend just has packages, but we'll need to get a boilerplate React frontend in TypeScript setup
- Note: previously `create-react-app` made boilerplate React app in JavaScript, but it is deprecated now
- These links might help:
   - https://react.dev/learn/typescript
   - https://react.dev/learn/add-react-to-an-existing-project

**Comment by maxwellmlin** [comment]
I like [Chakra UI](https://v2.chakra-ui.com/). Has a tight set of components to ensure consistent design.

**Comment by ben594** [comment]
I think this can be used to get the boilerplate code and stuff started: https://vitejs.dev/guide/
